version: '3'

services:
  
  frontend:
      container_name: frontend
      build:
        context: ./frontend-service/
      ports:
      - '5001:5000'
      depends_on:
      - backend
      environment:
      - SERVICE_URL=http://backend:5002

  backend:
      container_name: backend
      build:
        context: ./backend-service/
      ports:
      - '5002:5000'